# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:

steps:
- task: Gradle@2
  displayName: 'gradlew assembleDebug'
  inputs:
    gradleWrapperFile: 'MobileApp/SourceCode -Android/gradlew'
    workingDirectory: 'MobileApp/SourceCode -Android'
    tasks: assembleDebug
    publishJUnitResults: false
    checkStyleRunAnalysis: true
    findBugsRunAnalysis: true
    pmdRunAnalysis: true