trigger:
  none

variables:
- group: Mobile

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleRelease --stacktrace'

- task: AndroidSigning@3 
  inputs:
    apkFiles: '**/*.apk' 
    apksign: true 
    apksignerKeystoreFile: '$(keystore file)' 
    apksignerKeystorePassword: '$(password)' 
    apksignerKeystoreAlias: '$(alias)'
    apksignerKeyPassword: '$(password)'
    # Suppression de apksignerArguments pour éviter la confusion


- task: CopyFiles@2
  inputs:
    Contents: '**/*.apk' # Utilisez Contents pour spécifier les fichiers à copier
    TargetFolder: '$(build.artifactStagingDirectory)'
    Overwrite: true


- task: PublishBuildArtifacts@1
  inputs:
    PathToPublish: '$(build.artifactStagingDirectory)' # Assurez-vous que ce chemin est correct
    ArtifactName: 'apks'
    PublishLocation: 'container'

